# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(blank=True, max_length=20, null=True)),
                ('vacation_time', models.DateField(blank=True, null=True)),
                ('vacation_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vacation_record',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='employeeinformation',
            options={'managed': False, 'verbose_name': '\u5458\u5de5\u4fe1\u606f', 'verbose_name_plural': '\u5458\u5de5\u4fe1\u606f'},
        ),
    ]
