# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.CharField(default=12, max_length=2),
            preserve_default=False,
        ),
    ]
